package com.xworkz.operations.boot;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

public class Dams {

	public static void main(String[] args) {

		Collection<String> damsInKarnataka = new ArrayList<String>();
		damsInKarnataka.add("Almatti");
		damsInKarnataka.add("Basava Sagara(Narayanpur)");
		damsInKarnataka.add("Raja Lakhamagowda");
		damsInKarnataka.add("Renuka Sagara");
		damsInKarnataka.add("Vani Vilasa Sagara");
		damsInKarnataka.add("Upper Tunga");
		damsInKarnataka.add("Bhadra");
		damsInKarnataka.add("Tungabhadra");
		damsInKarnataka.add("Hemavathi Reservoir");
		damsInKarnataka.add("Kabini Reservoir");
		damsInKarnataka.add("Harangi Reservoir");
		damsInKarnataka.add("Krishna Raja Sagara");
		damsInKarnataka.add("Linganamakki");
		damsInKarnataka.add("Chakra Reservoir");
		damsInKarnataka.add("Savehaklu Reservoir");
		damsInKarnataka.add("Mani Reservoir");
		damsInKarnataka.add("Supa");
		damsInKarnataka.add("Kodasalli");
		damsInKarnataka.add("Kadra");
		damsInKarnataka.add("Shanti Sagara");
		damsInKarnataka.add("Karanja");

		Collection<String> damsInAndhraPradesh = new ArrayList<String>();// 129s
		damsInAndhraPradesh.add("Ahobilam / Penna Ahobilam (Dr. K.S.P.A.B.R.)");
		damsInAndhraPradesh.add("Akkapalem");
		damsInAndhraPradesh.add("Alaganoor");
		damsInAndhraPradesh.add("Ananthasagarm");
		damsInAndhraPradesh.add("Andhra");
		damsInAndhraPradesh.add("Arniar");
		damsInAndhraPradesh.add("Bahuda");
		damsInAndhraPradesh.add("Bhairavanithippa");
		damsInAndhraPradesh.add("Bhupathipalem");
		damsInAndhraPradesh.add("Buggavagu");
		damsInAndhraPradesh.add("Buggavanka");
		damsInAndhraPradesh.add("Bukkapatnam");
		damsInAndhraPradesh.add("Chagallu Barrage");
		damsInAndhraPradesh.add("Cheyyeru / Annamayya");
		damsInAndhraPradesh.add("Chinnarayaswamy Gudi /Chennaraya");
		damsInAndhraPradesh.add("Chintakuntavagu");
		damsInAndhraPradesh.add("Chitravathi");
		damsInAndhraPradesh.add("Cumbum");
		damsInAndhraPradesh.add("Dharmavaram");
		damsInAndhraPradesh.add("Donkarai ( S.H.E.S)");
		damsInAndhraPradesh.add("Eguva Thamballa Palli - Cheruvu");
		damsInAndhraPradesh.add("Forebay Lower Sileru ( S.H.E.S)");
		damsInAndhraPradesh.add("Gajuladinne (Sanjeevaiah Sagar)");
		damsInAndhraPradesh.add("Ahobilam / Penna Ahobilam (Dr. K.S.P.A.B.R.)");
		damsInAndhraPradesh.add("Gandicheruvu (Dist-Prakasam)");
		damsInAndhraPradesh.add("Gandipalem /Pcr Gandipalem");
		damsInAndhraPradesh.add("Ghambiramgedda");
		damsInAndhraPradesh.add("Gooty Tank");
		damsInAndhraPradesh.add("Gorakallu");
		damsInAndhraPradesh.add("Gundlakamma");
		damsInAndhraPradesh.add("Gundlamotu	");
		damsInAndhraPradesh.add("Guntawada Main");
		damsInAndhraPradesh.add("Haresamudram Big");
		damsInAndhraPradesh.add("Hiramandalam");
		damsInAndhraPradesh.add("Jajigedda");
		damsInAndhraPradesh.add("Jalakanur");
		damsInAndhraPradesh.add("Jalleru");
		damsInAndhraPradesh.add("Jhanjhavathi / Janjavathi");
		damsInAndhraPradesh.add("Kakarla");
		damsInAndhraPradesh.add("Kalangi");
		damsInAndhraPradesh.add("Kalinga Dal");
		damsInAndhraPradesh.add("Kalyani");
		damsInAndhraPradesh.add("Kampasamudram New");
		damsInAndhraPradesh.add("Kandaleru /Kandaleru");
		damsInAndhraPradesh.add("Kanelal Tank");
		damsInAndhraPradesh.add("Kanigiri");
		damsInAndhraPradesh.add("Konam");
		damsInAndhraPradesh.add("Kovvadakalva");
		damsInAndhraPradesh.add("Krishnapuram (Chittor)");
		damsInAndhraPradesh.add("Kumili");
		damsInAndhraPradesh.add("Kushavathi");
		damsInAndhraPradesh.add("Lower Sagileru");
		damsInAndhraPradesh.add("Madakasira");
		damsInAndhraPradesh.add("Maddigedda");
		damsInAndhraPradesh.add("Madduvalasa");
		damsInAndhraPradesh.add("Mallimadugu");
		damsInAndhraPradesh.add("Marala");
		damsInAndhraPradesh.add("Matchukota Balancing Reservoir");
		damsInAndhraPradesh.add("Midpennar Stage-I/Mid-Pennar");
		damsInAndhraPradesh.add("Mopadu");
		damsInAndhraPradesh.add("Muraripalli / Mararipalli");
		damsInAndhraPradesh.add("Musurumilli /Musurmilli");
		damsInAndhraPradesh.add("Mylavaram");
		damsInAndhraPradesh.add("N.T.R. , Thatiparthi(V), Madugula (M)");
		damsInAndhraPradesh.add("Nagurur");
		damsInAndhraPradesh.add("Nakkalagandi");
		damsInAndhraPradesh.add("Narayanapuram");
		damsInAndhraPradesh.add("Nellore");
		damsInAndhraPradesh.add("P.T.Cheruvu");
		damsInAndhraPradesh.add("Paleru ,Owk");
		damsInAndhraPradesh.add("Pampa");
		damsInAndhraPradesh.add("Panthulu Cheruvu");
		damsInAndhraPradesh.add("Paya Cheruvu");
		damsInAndhraPradesh.add("Pedaballi");
		damsInAndhraPradesh.add("Pedda Cheruvu , Nagasamudram");
		damsInAndhraPradesh.add("Pedda Rayala Cheruvu");
		damsInAndhraPradesh.add("Peddabadava, Tulasikrishan	");
		damsInAndhraPradesh.add("Peddagedda");
		damsInAndhraPradesh.add("Peddayetivanka, Annupal");
		damsInAndhraPradesh.add("Pedderu");
		damsInAndhraPradesh.add("Pendekallu");
		damsInAndhraPradesh.add("Pendlur");
		damsInAndhraPradesh.add("Peruru");
		damsInAndhraPradesh.add("Pincha");
		damsInAndhraPradesh.add("Pittakayagulla");
		damsInAndhraPradesh.add("Polavaram");
		damsInAndhraPradesh.add("Pulichintala");
		damsInAndhraPradesh.add("Raiwada");
		damsInAndhraPradesh.add("Rallapadu");
		damsInAndhraPradesh.add("Ramathirtham");
		damsInAndhraPradesh.add("Rayalacheruvu");
		damsInAndhraPradesh.add("SPVBS");
		damsInAndhraPradesh.add("Sadasivakona");
		damsInAndhraPradesh.add("Sancherla");
		damsInAndhraPradesh.add("Sankarayalapeta");
		damsInAndhraPradesh.add("Savisettipalli");
		damsInAndhraPradesh.add("Seethai Cheru, Seethaipally");
		damsInAndhraPradesh.add("Siddalagandi");
		damsInAndhraPradesh.add("Somasila");
		damsInAndhraPradesh.add("Sreerangarayani Cheruvu");
		damsInAndhraPradesh.add("Sri Subbaraya Sagar");
		damsInAndhraPradesh.add("Sri Tenneti Viswanatham Pedderu");
		damsInAndhraPradesh.add("Surampalem");
		damsInAndhraPradesh.add("T.Sundupalli");
		damsInAndhraPradesh.add("Tajangi , Tajangi(V)");
		damsInAndhraPradesh.add("Thadukuvagu");
		damsInAndhraPradesh.add("Thammileru");
		damsInAndhraPradesh.add("Thandava(Sri Raja Sagi Suryanarayana Raju (Srssr)");
		damsInAndhraPradesh.add("Thatipudi");
		damsInAndhraPradesh.add("Thippayapalem");
		damsInAndhraPradesh.add("Turimella Reservoir");
		damsInAndhraPradesh.add("Upper Pennar");
		damsInAndhraPradesh.add("Urakagedda , Sankaram (V), Madugula(M)");
		damsInAndhraPradesh.add("Vanaka Badigedda");
		damsInAndhraPradesh.add("Varadaraja Swamy Gudi");
		damsInAndhraPradesh.add("Varaha");
		damsInAndhraPradesh.add("Varikunta");
		damsInAndhraPradesh.add("Veligallu");
		damsInAndhraPradesh.add("Veligonda");
		damsInAndhraPradesh.add("Velugodu");
		damsInAndhraPradesh.add("Vengalaraya Sagar");
		damsInAndhraPradesh.add("Vottigadda");
		damsInAndhraPradesh.add("Vyasasamudram");
		damsInAndhraPradesh.add("Y.T.Cheruvu");
		damsInAndhraPradesh.add("Yeddula Eswaraiah GandiKoata");
		damsInAndhraPradesh.add("Yeleru");
		damsInAndhraPradesh.add("Yerrakalva");
		damsInAndhraPradesh.add("Yogivemana");
		damsInAndhraPradesh.add("Zurreru");

		Collection<String> damsInArunachal = new ArrayList<String>();
		damsInArunachal.add("Ranganadi");
		damsInArunachal.add("Subansiri Lower HE (Nhpc)");

		Collection<String> damsInAssam = new ArrayList<String>();
		damsInAssam.add("Karbi Langpi");
		damsInAssam.add("Umrong");

		Collection<String> damsInBihar = new ArrayList<String>();// 129s
		damsInBihar.add("Ajan");
		damsInBihar.add("Amrity");
		damsInBihar.add("Badua");
		damsInBihar.add("Barnar");
		damsInBihar.add("Baskund");
		damsInBihar.add("Belharna");
		damsInBihar.add("Bilasi");
		damsInBihar.add("Chandan");
		damsInBihar.add("Durgawati");
		damsInBihar.add("Gaighat");
		damsInBihar.add("Jalkund");
		damsInBihar.add("Job");
		damsInBihar.add("Kailash Ghati");
		damsInBihar.add("Khargpur Lake");
		damsInBihar.add("Kohira");
		damsInBihar.add("Kolmahadeo");
		damsInBihar.add("Morwy");
		damsInBihar.add("Nagi");
		damsInBihar.add("Nakti (Bihar)");
		damsInBihar.add("Phulwaria");
		damsInBihar.add("Sindhwarni	");
		damsInBihar.add("Srikhandi");
		damsInBihar.add("Upper Kiul");

		Collection<String> damsInChattisgarh = new ArrayList<String>();// 129s
		damsInChattisgarh.add("Hasdeo Bango (Minimata)");
		damsInChattisgarh.add("Agariya");
		damsInChattisgarh.add("Adpather");
		damsInChattisgarh.add("Ajabnagar");
		damsInChattisgarh.add("Amabeda");
		damsInChattisgarh.add("Amachuwa");
		damsInChattisgarh.add("Amakhokhra");
		damsInChattisgarh.add("Amakoni");
		damsInChattisgarh.add("Amgaon");
		damsInChattisgarh.add("Amhar");
		damsInChattisgarh.add("Aondhi");
		damsInChattisgarh.add("Auramimunda");
		damsInChattisgarh.add("Ayabhandha");
		damsInChattisgarh.add("Badauli");
		damsInChattisgarh.add("Badesathi");
		damsInChattisgarh.add("Badra");
		damsInChattisgarh.add("Badrika Ashram");
		damsInChattisgarh.add("Ballar");
		damsInChattisgarh.add("Banjaridand");
		damsInChattisgarh.add("Banki");
		damsInChattisgarh.add("Bankipur");
		damsInChattisgarh.add("Barat Sagar");
		damsInChattisgarh.add("Bardar");
		damsInChattisgarh.add("Barkela");
		damsInChattisgarh.add("Barnai");
		damsInChattisgarh.add("Barota");
		damsInChattisgarh.add("Barpara");
		damsInChattisgarh.add("Batra");
		damsInChattisgarh.add("Beherakhar (Banjar )");
		damsInChattisgarh.add("Belbehra");
		damsInChattisgarh.add("Belhari");
		damsInChattisgarh.add("Bhagwantola");
		damsInChattisgarh.add("Bhopali");
		damsInChattisgarh.add("Bhoramdeo");
		damsInChattisgarh.add("Bhortola");
		damsInChattisgarh.add("Bhulsi");
		damsInChattisgarh.add("Bhursatoli");
		damsInChattisgarh.add("Binjali");
		damsInChattisgarh.add("Bisrampuri");
		damsInChattisgarh.add("Bordi");
		damsInChattisgarh.add("Chaker");
		damsInChattisgarh.add("Chamat");
		damsInChattisgarh.add("Champi");
		damsInChattisgarh.add("Chandra Nagar");
		damsInChattisgarh.add("Chanti");
		damsInChattisgarh.add("Charcha");
		damsInChattisgarh.add("Charpara");
		damsInChattisgarh.add("Chhirpani");
		damsInChattisgarh.add("Chhota Palgi");
		damsInChattisgarh.add("Chhuwari Pali");
		damsInChattisgarh.add("Chikhali");
		damsInChattisgarh.add("Chilputi");
		damsInChattisgarh.add("Chiniya");
		damsInChattisgarh.add("Chourasiya");
		damsInChattisgarh.add("Churiyapat");
		damsInChattisgarh.add("Dandgaon");
		damsInChattisgarh.add("Darki");
		damsInChattisgarh.add("Darritola");
		damsInChattisgarh.add("Deogaon");
		damsInChattisgarh.add("Deokatta");
		damsInChattisgarh.add("Deoripali");
		damsInChattisgarh.add("Dhab");
		damsInChattisgarh.add("Dhamni No. I");
		damsInChattisgarh.add("Dhanras");
		damsInChattisgarh.add("Dhara");
		damsInChattisgarh.add("Dhawanpur");
		damsInChattisgarh.add("Dhupkot");
		damsInChattisgarh.add("Diona");
		damsInChattisgarh.add("Doura");
		damsInChattisgarh.add("Dudhawa");
		damsInChattisgarh.add("Fatehpur");
		damsInChattisgarh.add("Fulwari");
		damsInChattisgarh.add("Gagnai");
		damsInChattisgarh.add("Ganeshpur");
		damsInChattisgarh.add("Gangpur");
		damsInChattisgarh.add("Ganiyari");
		damsInChattisgarh.add("Gatatola");
		damsInChattisgarh.add("Gej");
		damsInChattisgarh.add("Ghatoi");
		damsInChattisgarh.add("Ghoghra");
		damsInChattisgarh.add("Ghongha");
		damsInChattisgarh.add("Ghughwa");
		damsInChattisgarh.add("Ghumarapadar");
		damsInChattisgarh.add("Ghunghutta");
		damsInChattisgarh.add("Gobari");
		damsInChattisgarh.add("Gondli");
		damsInChattisgarh.add("Gouri");
		damsInChattisgarh.add("Gunderdehi");
		damsInChattisgarh.add("Gursia");
		damsInChattisgarh.add("Hathlewa");
		damsInChattisgarh.add("Jagannathpur");
		damsInChattisgarh.add("Jagatpur");
		damsInChattisgarh.add("Jamdih");
		damsInChattisgarh.add("Jhalpi");
		damsInChattisgarh.add("Jhingo");
		damsInChattisgarh.add("Jhumka");
		damsInChattisgarh.add("Junwani");
		damsInChattisgarh.add("Kachhod");
		damsInChattisgarh.add("Kadna");
		damsInChattisgarh.add("Kalidaraha");

		Collection<String> damsInGoa = new ArrayList<String>();
		damsInGoa.add("Anjunam");
		damsInGoa.add("M.I");
		damsInGoa.add("Salaulim");

		Collection<String> damsInHaryana = new ArrayList<String>();
		damsInHaryana.add("kaushalya");

		Collection<String> damsInHimachalPradesh = new ArrayList<String>();
		damsInHimachalPradesh.add("Baira Siul");
		damsInHimachalPradesh.add("Bassi");
		damsInHimachalPradesh.add("Bhakra");
		damsInHimachalPradesh.add("Chamera");
		damsInHimachalPradesh.add("Karchham");
		damsInHimachalPradesh.add("Kol");
		damsInHimachalPradesh.add("Largi");
		damsInHimachalPradesh.add("Malana");
		damsInHimachalPradesh.add("Nathpa Jhakri");
		damsInHimachalPradesh.add("Pandoh");
		damsInHimachalPradesh.add("Parbati");
		damsInHimachalPradesh.add("Pong");
		damsInHimachalPradesh.add("Sawra- Kuddu");

		Collection<String> damsInJharkand = new ArrayList<String>();
		damsInJharkand.add("Amanat");
		damsInJharkand.add("Anjanwa");
		damsInJharkand.add("Anraj");
		damsInJharkand.add("Baksa");
		damsInJharkand.add("Bandha");
		damsInJharkand.add("kaushalya");
		damsInJharkand.add("Baranadi");
		damsInJharkand.add("Barhi");
		damsInJharkand.add("Basuki");
		damsInJharkand.add("Batane");
		damsInJharkand.add("Batre");
		damsInJharkand.add("Bhairwa");
		damsInJharkand.add("Bhavnikhand");
		damsInJharkand.add("Bhutanduba");
		damsInJharkand.add("Bucha Opa");
		damsInJharkand.add("Burhai");
		damsInJharkand.add("Chandil");
		damsInJharkand.add("Chatania Ghat");
		damsInJharkand.add("Chinda");
		damsInJharkand.add("Chirka");
		damsInJharkand.add("Danro");
		damsInJharkand.add("Dhankai");
		damsInJharkand.add("Dhansingtoli");
		damsInJharkand.add("Dhulki");
		damsInJharkand.add("Diggalpahari");
		damsInJharkand.add("Garhi");
		damsInJharkand.add("Getalsud");
		damsInJharkand.add("Ghaghra");
		damsInJharkand.add("Gonda");
		damsInJharkand.add("Hatia");
		damsInJharkand.add("Hiru");
		damsInJharkand.add("Icha");
		damsInJharkand.add("Jaipur");
		damsInJharkand.add("Jamunia");
		damsInJharkand.add("Jenasai");
		damsInJharkand.add("Jharjhara");
		damsInJharkand.add("Kanhar");
		damsInJharkand.add("Kans");
		damsInJharkand.add("Kansjore");
		damsInJharkand.add("Karawani");
		damsInJharkand.add("Katri");
		damsInJharkand.add("Kesho");
		damsInJharkand.add("Khudia");
		damsInJharkand.add("Konar");
		damsInJharkand.add("Larwa");
		damsInJharkand.add("Latratu");
		damsInJharkand.add("Left Banki");
		damsInJharkand.add("Lorgara");
		damsInJharkand.add("Lotia");
		damsInJharkand.add("Maithon");
		damsInJharkand.add("Malay");
		damsInJharkand.add("Masanjor");
		damsInJharkand.add("Masaria");
		damsInJharkand.add("Murahir");
		damsInJharkand.add("Nakti");
		damsInJharkand.add("Nalkari");
		damsInJharkand.add("Nandini");
		damsInJharkand.add("North Koel");
		damsInJharkand.add("Palna");
		damsInJharkand.add("Panchat");
		damsInJharkand.add("Panchkhero");
		damsInJharkand.add("Pandarwa");
		damsInJharkand.add("Paras");
		damsInJharkand.add("Punasi");
		damsInJharkand.add("Raisa");
		damsInJharkand.add("Ramrekha");
		damsInJharkand.add("Salaiya");
		damsInJharkand.add("Satpotka");
		damsInJharkand.add("Sitaram");
		damsInJharkand.add("Sonua");
		damsInJharkand.add("Sudhari Nala");
		damsInJharkand.add("Sugathan");
		damsInJharkand.add("Sukri");
		damsInJharkand.add("Sunder");
		damsInJharkand.add("Surangi");
		damsInJharkand.add("Suryodi");
		damsInJharkand.add("Tahlay");
		damsInJharkand.add("Tajna");
		damsInJharkand.add("Tapkara");
		damsInJharkand.add("Temrain");
		damsInJharkand.add("Tenughat");
		damsInJharkand.add("Tilaiya");
		damsInJharkand.add("Torai");
		damsInJharkand.add("Torlow");
		damsInJharkand.add("Upper Shankh");

		Collection<String> damsInKerala = new ArrayList<String>();
		damsInKerala.add("Anathode Flanking (Eb)");
		damsInKerala.add("Anayirangal");
		damsInKerala.add("Aruvikkara");
		damsInKerala.add("Azhutha");
		damsInKerala.add("Cavaiar");
		damsInKerala.add("Cheruthoni");
		damsInKerala.add("Chimoni");
		damsInKerala.add("Chulliar (Gayathri Stage-II) (Id)");
		damsInKerala.add("Erattayar");
		damsInKerala.add("Idamalayar");
		damsInKerala.add("Idukki");
		damsInKerala.add("Kakkayam");
		damsInKerala.add("Kakki");
		damsInKerala.add("Kallada");
		damsInKerala.add("Kallar");
		damsInKerala.add("Kallarkutty");
		damsInKerala.add("Kanhira");
		damsInKerala.add("Karapuzha");
		damsInKerala.add("Kosani Saddle");
		damsInKerala.add("Kottagiri Saddle");
		damsInKerala.add("Kulamavu");
		damsInKerala.add("Kullar (Sabarigiri Aug.)");
		damsInKerala.add("Kundala");
		damsInKerala.add("Kutiyar Diversion");
		damsInKerala.add("Kuttiyadi");
		damsInKerala.add("Kuttiyadi Aug. Saddle");
		damsInKerala.add("Kuttiyadi Spillway");
		damsInKerala.add("Lower Periyar");
		damsInKerala.add("Madupetty");
		damsInKerala.add("Malampuzha");
		damsInKerala.add("Malankara");
		damsInKerala.add("Mangalam");
		damsInKerala.add("Meenar");
		damsInKerala.add("Meenkara");
		damsInKerala.add("Narakakanam Diversion");
		damsInKerala.add("Near Kottagiri Saddle");
		damsInKerala.add("Neyyar");
		damsInKerala.add("Pamba");
		damsInKerala.add("Parambikulam");
		damsInKerala.add("Peechi");
		damsInKerala.add("Peppara");
		damsInKerala.add("Periyar");
		damsInKerala.add("Peruvaripallam");
		damsInKerala.add("Ponmudi");
		damsInKerala.add("Poomala");
		damsInKerala.add("Poringalkuthu");
		damsInKerala.add("Pothundy");
		damsInKerala.add("Sengulam");
		damsInKerala.add("Sholayar");
		damsInKerala.add("Sholayar Flanking");
		damsInKerala.add("Siruvani");
		damsInKerala.add("Tunacadavu");
		damsInKerala.add("Upper Moozhiyar");
		damsInKerala.add("Upper Moozhiyar Spillway");
		damsInKerala.add("Vazhany");
		damsInKerala.add("Vazhikkadavu");
		damsInKerala.add("Veluthoda Forebay");
		damsInKerala.add("Walayar");

		Collection<String> damsInGujarat = new ArrayList<String>();
		damsInGujarat.add("Aamli Chharchhoda");
		damsInGujarat.add("Abhalwad");
		damsInGujarat.add("Adhia");
		damsInGujarat.add("Adhochhani");
		damsInGujarat.add("Adhoi- I");
		damsInGujarat.add("Adpur");
		damsInGujarat.add("Advana");
		damsInGujarat.add("Aji I");
		damsInGujarat.add("Aji II");
		damsInGujarat.add("Aji III");
		damsInGujarat.add("Ajwa");
		damsInGujarat.add("Alan Sagar");
		damsInGujarat.add("Amalwant");
		damsInGujarat.add("Ambajal");
		damsInGujarat.add("Ambakui");
		damsInGujarat.add("Ambala");
		damsInGujarat.add("Ambani Khodiar");
		damsInGujarat.add("Ambaradi");
		damsInGujarat.add("Amirpur");
		damsInGujarat.add("Anandapar");
		damsInGujarat.add("Andhariparpata");
		damsInGujarat.add("Angianawa");
		damsInGujarat.add("Anida");
		damsInGujarat.add("Arrni");
		damsInGujarat.add("Badargadh");
		damsInGujarat.add("Badi-Padva");
		damsInGujarat.add("Bagad");
		damsInGujarat.add("Baladhor");
		damsInGujarat.add("Balamdi");
		damsInGujarat.add("Balapar Budadro");
		damsInGujarat.add("Baldeva");
		damsInGujarat.add("Baliyawad");
		damsInGujarat.add("Bamanbore");
		damsInGujarat.add("Bambhanka");
		damsInGujarat.add("Bandhara");
		damsInGujarat.add("Bandi");
		damsInGujarat.add("Bangawadi");
		damsInGujarat.add("Baranda");
		damsInGujarat.add("Baukha");
		damsInGujarat.add("Bedi");
		damsInGujarat.add("Bela");
		damsInGujarat.add("Berachiya");
		damsInGujarat.add("Bhadar");
		damsInGujarat.add("Bhadreshwar");
		damsInGujarat.add("Bhaguda");
		damsInGujarat.add("Bhandaria");
		damsInGujarat.add("Bhanmer");
		damsInGujarat.add("Bharad");
		damsInGujarat.add("Bharapar");
		damsInGujarat.add("Bharudia");
		damsInGujarat.add("Bhimdad");
		damsInGujarat.add("Bhuj");
		damsInGujarat.add("Bhuki");
		damsInGujarat.add("Bodi");
		damsInGujarat.add("Borsi");
		damsInGujarat.add("Brahmani");
		damsInGujarat.add("Burkhan");
		damsInGujarat.add("Butta");
		damsInGujarat.add("Chachka");
		damsInGujarat.add("Chandrabhaga");
		damsInGujarat.add("Chang");
		damsInGujarat.add("Chavadka");
		damsInGujarat.add("Chhaparvadi");
		damsInGujarat.add("Chimnabai-Lake");
		damsInGujarat.add("Chonda");
		damsInGujarat.add("Chopadavav");
		damsInGujarat.add("Chorwadala");
		damsInGujarat.add("Dabahada");
		damsInGujarat.add("Dabasang");
		damsInGujarat.add("Dadar");
		damsInGujarat.add("Daiminisar");
		damsInGujarat.add("Dodfavanta");
		damsInGujarat.add("Domda M.I");
		damsInGujarat.add("Facharia");
		damsInGujarat.add("Faddanbeti");
		damsInGujarat.add("Fakirwadi");
		damsInGujarat.add("Falku");
		damsInGujarat.add("Faradi");
		damsInGujarat.add("Farera");
		damsInGujarat.add("Fatehgadh");
		damsInGujarat.add("Fodaraness");
		damsInGujarat.add("Fulzar");
		damsInGujarat.add("Gadhada- Rasaji");
		damsInGujarat.add("Gadhki");
		damsInGujarat.add("Gajansagar");
		damsInGujarat.add("Gajod");
		damsInGujarat.add("Gaurishankar");
		damsInGujarat.add("Gautameshwar");
		damsInGujarat.add("Gebanshapir");
		damsInGujarat.add("Ghee");
		damsInGujarat.add("Ghela Somnath");
		damsInGujarat.add("Ghodadharoi");
		damsInGujarat.add("Godechi");
		damsInGujarat.add("Godhatad");
		damsInGujarat.add("Gokhalana");
		damsInGujarat.add("Goma");
		damsInGujarat.add("Gondali");
		damsInGujarat.add("Goyala");
		damsInGujarat.add("Goyasundal");
		damsInGujarat.add("Gugariyana");
		damsInGujarat.add("Guhai");
		damsInGujarat.add("Guneli");
		damsInGujarat.add("Hadaf");
		damsInGujarat.add("Halara");
		damsInGujarat.add("Hamapur");
		damsInGujarat.add("Hamipara");
		damsInGujarat.add("Hanol");
		damsInGujarat.add("Hansthal");
		damsInGujarat.add("Harwant");
		damsInGujarat.add("Hatadi");
		damsInGujarat.add("Hathasani");
		damsInGujarat.add("Hathidra");
		damsInGujarat.add("Hathmati");
		damsInGujarat.add("Ingorala");
		damsInGujarat.add("Isar");
		damsInGujarat.add("Ishwariya");
		damsInGujarat.add("Jadawas");
		damsInGujarat.add("Jaday");

		Collection<String> damsInMadhyaPradesh = new ArrayList<String>();
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");
		damsInMadhyaPradesh.add("Amanat");

		Collection<String> damsInMaharashtra = new ArrayList<String>();
		damsInMaharashtra.add("Dhamapur");
		damsInMaharashtra.add("Vihar");
		damsInMaharashtra.add("Ekrukh");
		damsInMaharashtra.add("Shirsufal");
		damsInMaharashtra.add("Tulshi");
		damsInMaharashtra.add("Khadakwasla");
		damsInMaharashtra.add("Ashti");
		damsInMaharashtra.add("Mhaswad");
		damsInMaharashtra.add("Tansa");
		damsInMaharashtra.add("Shetfal");
		damsInMaharashtra.add("Khairbandha");
		damsInMaharashtra.add("Pathari");
		damsInMaharashtra.add("Chankapur");
		damsInMaharashtra.add("Ramtek");
		damsInMaharashtra.add("Chandpur");
		damsInMaharashtra.add("Walwan");
		damsInMaharashtra.add("Darna");
		damsInMaharashtra.add("Bodalkasa");
		damsInMaharashtra.add("Asolamendha");
		damsInMaharashtra.add("Shirvata");
		damsInMaharashtra.add("Thokarwadi");
		damsInMaharashtra.add("Chorkhamara");
		damsInMaharashtra.add("Ghorazari");
		damsInMaharashtra.add("Bhandardara");
		damsInMaharashtra.add("Bhatghar");
		damsInMaharashtra.add("Mulshi");
		damsInMaharashtra.add("Ghanewadi");
		damsInMaharashtra.add("Visapur");

		Collection<String> damsInManipur = new ArrayList<String>();

		damsInManipur.add("Khoupum");
		damsInManipur.add("Khuga");
		damsInManipur.add("Singda");
		damsInManipur.add("Thoubal");

		Collection<String> damsInMeghalaya = new ArrayList<String>();

		damsInMeghalaya.add("Khandong");
		damsInMeghalaya.add("Kyrdemkulai");
		damsInMeghalaya.add("Mawphlang");
		damsInMeghalaya.add("Myntdu-Leshka");
		damsInMeghalaya.add("Nongkhyllem");
		damsInMeghalaya.add("Umiam");
		damsInMeghalaya.add("Umtru");

		Collection<String> damsInMizoram = new ArrayList<String>();

		damsInMizoram.add("Serlui B");
		damsInMizoram.add("Tuirial");

		Collection<String> damsInNagaland = new ArrayList<String>();

		damsInNagaland.add("Doyang Hep");

		Collection<String> damsInOdisha = new ArrayList<String>();

		damsInOdisha.add("Alubani");
		damsInOdisha.add("Aradei");
		damsInOdisha.add("Arikul");
		damsInOdisha.add("Badabandha");
		damsInOdisha.add("Badanalla");
		damsInOdisha.add("Badjore");
		damsInOdisha.add("Baghalati");
		damsInOdisha.add("Baghjharan");
		damsInOdisha.add("Baghua (MI)");
		damsInOdisha.add("Baghua");
		damsInOdisha.add("Balaskumpa");
		damsInOdisha.add("Balimela");
		damsInOdisha.add("Bankabal");
		damsInOdisha.add("Banksal");
		damsInOdisha.add("Baura");
		damsInOdisha.add("Bautia");
		damsInOdisha.add("Bedapada");
		damsInOdisha.add("Behera");
		damsInOdisha.add("Benikpur");
		damsInOdisha.add("Bhagirijhala");
		damsInOdisha.add("Bhallugahi");
		damsInOdisha.add("Bhaluguda");
		damsInOdisha.add("Bhanjanagar");
		damsInOdisha.add("Bhaskel");
		damsInOdisha.add("Bhatrajore");
		damsInOdisha.add("Bhetabar");
		damsInOdisha.add("Bhitiri Bediguda");
		damsInOdisha.add("Budhabudiani");
		damsInOdisha.add("Chhamundia");
		damsInOdisha.add("Chhatenjore");
		damsInOdisha.add("Chheligada");
		damsInOdisha.add("Dadara Ghati");
		damsInOdisha.add("Daha(OD)");
		damsInOdisha.add("Damsal");
		damsInOdisha.add("Dasamanthapur");
		damsInOdisha.add("Debijharan");
		damsInOdisha.add("Deo(OD)");
		damsInOdisha.add("Deojharan");
		damsInOdisha.add("Deras");
		damsInOdisha.add("Derjang");
		damsInOdisha.add("Dhanei");
		damsInOdisha.add("Dhulipaunsia");
		damsInOdisha.add("Domkutch");
		damsInOdisha.add("Dumerbahal");
		damsInOdisha.add("Gaikhai(Minor)");
		damsInOdisha.add("Ganianalla");
		damsInOdisha.add("Garh");
		damsInOdisha.add("Gayapathar");
		damsInOdisha.add("Ghagara");
		damsInOdisha.add("Ghatakeswar");
		damsInOdisha.add("Ghodahada");
		damsInOdisha.add("Gohira");
		damsInOdisha.add("Goibali");
		damsInOdisha.add("Gundurapasi");
		damsInOdisha.add("Gurlijore");
		damsInOdisha.add("HATIANALLA M.I.P");
		damsInOdisha.add("Hadua");
		damsInOdisha.add("Haguri");
		damsInOdisha.add("Haladia");
		damsInOdisha.add("Hanumantia");
		damsInOdisha.add("Harabhangi");
		damsInOdisha.add("Hariharjore");
		damsInOdisha.add("Haripur");
		damsInOdisha.add("Hirakud");
		damsInOdisha.add("Indrawati");
		damsInOdisha.add("Jagadala");
		damsInOdisha.add("Jaigarh");
		damsInOdisha.add("Jalaput");
		damsInOdisha.add("Jambhira");
		damsInOdisha.add("Jamboonala");
		damsInOdisha.add("Jamuna Bundha");
		damsInOdisha.add("Jaunria");
		damsInOdisha.add("Jharanai");
		damsInOdisha.add("Jharbandha");
		damsInOdisha.add("Jhumuka");
		damsInOdisha.add("Jodabadia");
		damsInOdisha.add("Kakudajodi");
		damsInOdisha.add("Kalakala");
		damsInOdisha.add("Kalijodi");
		damsInOdisha.add("Kalo");
		damsInOdisha.add("Kangani");
		damsInOdisha.add("Kanheinalla");
		damsInOdisha.add("Kanjhari");
		damsInOdisha.add("Kansabansa");
		damsInOdisha.add("Kansbahal");
		damsInOdisha.add("Kanteijhara");
		damsInOdisha.add("Kantesir");
		damsInOdisha.add("Kanupur");
		damsInOdisha.add("Kapur");
		damsInOdisha.add("Karada");
		damsInOdisha.add("Karanjkote");
		damsInOdisha.add("Khadakhai");
		damsInOdisha.add("Khajuria");
		damsInOdisha.add("Khandijharan");
		damsInOdisha.add("Khasbahal");
		damsInOdisha.add("Khuntapada");
		damsInOdisha.add("Kiajhar");
		damsInOdisha.add("Kodabhal");
		damsInOdisha.add("Kodigam");
		damsInOdisha.add("Konheimunda");
		damsInOdisha.add("Koska");
		damsInOdisha.add("Kuanria");
		damsInOdisha.add("Kukurpeta");
		damsInOdisha.add("Kumbho");
		damsInOdisha.add("Kureijodi");
		damsInOdisha.add("Kusunpur");
		damsInOdisha.add("Laigam");
		damsInOdisha.add("Lakhaparbat");
		damsInOdisha.add("Laupal");
		damsInOdisha.add("Laxmipur");
		damsInOdisha.add("Liar");
		damsInOdisha.add("Lower Indra");
		damsInOdisha.add("Lower Suktal");
		damsInOdisha.add("Magara");
		damsInOdisha.add("Maharanisagar");
		damsInOdisha.add("Mahendratanaya");
		damsInOdisha.add("Mahisanalla");
		damsInOdisha.add("Malakangiri");
		damsInOdisha.add("Mandira");
		damsInOdisha.add("Manjhor");
		damsInOdisha.add("Marudi");
		damsInOdisha.add("Masina");
		damsInOdisha.add("Mathan Pal");
		damsInOdisha.add("Mathili");
		damsInOdisha.add("Muran");
		damsInOdisha.add("Nesa");
		damsInOdisha.add("Nimajhar Mip");
		damsInOdisha.add("Padampur");
		damsInOdisha.add("Paitagam");
		damsInOdisha.add("Panaskhal");
		damsInOdisha.add("Pani-Pailla");
		damsInOdisha.add("Pansapal");
		damsInOdisha.add("Parhal");
		damsInOdisha.add("Paunsia");
		damsInOdisha.add("Pilasalki");
		damsInOdisha.add("Pipal");
		damsInOdisha.add("Pitamahal");
		damsInOdisha.add("Podagada");
		damsInOdisha.add("Pokharia");
		damsInOdisha.add("Pratappur");
		damsInOdisha.add("Pujiladu");
		damsInOdisha.add("Raghubeda");
		damsInOdisha.add("Raghunath Sagar");
		damsInOdisha.add("Raijharan");
		damsInOdisha.add("Ramaguda");
		damsInOdisha.add("Ramiala");
		damsInOdisha.add("Randa");
		damsInOdisha.add("Remal");
		damsInOdisha.add("Rengali");
		damsInOdisha.add("Ret");
		damsInOdisha.add("Rissia");
		damsInOdisha.add("Rukura");
		damsInOdisha.add("Rungaon");
		damsInOdisha.add("Saipala");
		damsInOdisha.add("Salandi");
		damsInOdisha.add("Salia");
		damsInOdisha.add("Sanasialinai");
		damsInOdisha.add("Sanmachhakandana ");
		damsInOdisha.add("Sapua (Medium)");
		damsInOdisha.add("Sarapa");
		damsInOdisha.add("Saraphgarh");
		damsInOdisha.add("Satiguda");
		damsInOdisha.add("Sendhie");
		damsInOdisha.add("Soroda");
		damsInOdisha.add("Suhagi");
		damsInOdisha.add("Sunaghai");
		damsInOdisha.add("Sunamuhin");
		damsInOdisha.add("Sundar(OD)");
		damsInOdisha.add("Sunei");
		damsInOdisha.add("Talasara");
		damsInOdisha.add("Talkhol");
		damsInOdisha.add("Tangarakana");
		damsInOdisha.add("Telengiri(T.M.I.P)");
		damsInOdisha.add("Tenar");
		damsInOdisha.add("Tikarpada");
		damsInOdisha.add("Tilipada");
		damsInOdisha.add("Titilagarh(Stage- II)");
		damsInOdisha.add("Upper Jonk");
		damsInOdisha.add("Upper Kolab	");
		damsInOdisha.add("Upper Lanth");
		damsInOdisha.add("Upper Suktel");

		Collection<String> damsInPunjab = new ArrayList<String>();

		damsInPunjab.add("Chohal");
		damsInPunjab.add("Damsal");
		damsInPunjab.add("Dholbaha");
		damsInPunjab.add("Jainti");
		damsInPunjab.add("Janauri");
		damsInPunjab.add("Maili");
		damsInPunjab.add("Mirzapur");
		damsInPunjab.add("Patiari");
		damsInPunjab.add("Perch");
		damsInPunjab.add("Ranjit Sagar");
		damsInPunjab.add("Saleran");
		damsInPunjab.add("Shahpur Kandi");
		damsInPunjab.add("Siswan");
		damsInPunjab.add("Thana");

		Collection<String> damsInRajasthan = new ArrayList<String>();

		damsInRajasthan.add("Abhaypura");
		damsInRajasthan.add("Aklera Sagar");
		damsInRajasthan.add("Alnia");
		damsInRajasthan.add("Amli Kheda");
		damsInRajasthan.add("Angore");
		damsInRajasthan.add("Anwasa");
		damsInRajasthan.add("Arwar");
		damsInRajasthan.add("Atawara");
		damsInRajasthan.add("Babara");
		damsInRajasthan.add("Badgaon");
		damsInRajasthan.add("Bagolia");
		damsInRajasthan.add("Bajrang");
		damsInRajasthan.add("Banakiya");
		damsInRajasthan.add("Bandi");
		damsInRajasthan.add("Bankali");
		damsInRajasthan.add("Baradpura");
		damsInRajasthan.add("Baretha Bund");
		damsInRajasthan.add("Bari Mansarowar");
		damsInRajasthan.add("Barkheri");
		damsInRajasthan.add("Bassi");
		damsInRajasthan.add("Basundni");
		damsInRajasthan.add("Bethali");
		damsInRajasthan.add("Bhagora");
		damsInRajasthan.add("Bhagwatgardh");
		damsInRajasthan.add("Bhamri Tandi");
		damsInRajasthan.add("Bhanwar Semla");
		damsInRajasthan.add("Bhatia");
		damsInRajasthan.add("Bhimlat");
		damsInRajasthan.add("Bhimsagar");
		damsInRajasthan.add("Bhopal Sagar ");
		damsInRajasthan.add("Bhula");
		damsInRajasthan.add("Bilas");
		damsInRajasthan.add("Bisalpur");
		damsInRajasthan.add("Bithan");
		damsInRajasthan.add("Biya Pada");
		damsInRajasthan.add("Borda");
		damsInRajasthan.add("Boria");
		damsInRajasthan.add("Buchara");
		damsInRajasthan.add("Bundika Gothra");
		damsInRajasthan.add("Burdha");
		damsInRajasthan.add("Butri");
		damsInRajasthan.add("Chacha Kheri");
		damsInRajasthan.add("Chandelao");
		damsInRajasthan.add("Chandrabhaga");
		damsInRajasthan.add("Chandrana");
		damsInRajasthan.add("Bheru");
		damsInRajasthan.add("Chaparwara");
		damsInRajasthan.add("Kunty");
		damsInRajasthan.add("Chatra");
		damsInRajasthan.add("Chauli");
		damsInRajasthan.add("Chhapi");
		damsInRajasthan.add("Chikalwar");
		damsInRajasthan.add("Chittoli");
		damsInRajasthan.add("Choti-Tandi");
		damsInRajasthan.add("DANDIA");
		damsInRajasthan.add("Daya");
		damsInRajasthan.add("Deopura");
		damsInRajasthan.add("Deoriya");
		damsInRajasthan.add("Dheel");
		damsInRajasthan.add("Dhanta");
		damsInRajasthan.add("Dindoli");
		damsInRajasthan.add("Domti Kokra");
		damsInRajasthan.add("Dorai");
		damsInRajasthan.add("Dudka");
		damsInRajasthan.add("Dugari");
		damsInRajasthan.add("Dunglawani");
		damsInRajasthan.add("Fateh Sagar");
		damsInRajasthan.add("Gadola");
		damsInRajasthan.add("Gagrin");
		damsInRajasthan.add("Galai Sagar");
		damsInRajasthan.add("Galwa");
		damsInRajasthan.add("Galwania");
		damsInRajasthan.add("Gambhiri");
		damsInRajasthan.add("Gararda");
		damsInRajasthan.add("Girinanda");
		damsInRajasthan.add("Giroliya");
		damsInRajasthan.add("Girwar");
		damsInRajasthan.add("Godana");
		damsInRajasthan.add("Gopalpura");
		damsInRajasthan.add("Gosunda");
		damsInRajasthan.add("Govta");
		damsInRajasthan.add("Goyaka");
		damsInRajasthan.add("Gudha");
		damsInRajasthan.add("Gulandi");
		damsInRajasthan.add("Hamja Kheri");
		damsInRajasthan.add("Harish Chandra sagar");
		damsInRajasthan.add("Harro");
		damsInRajasthan.add("Harsora");
		damsInRajasthan.add("Hemavas Saddle");
		damsInRajasthan.add("Hemawas");
		damsInRajasthan.add("Himmatgarhi");
		damsInRajasthan.add("Hindlot");
		damsInRajasthan.add("Hingonia");
		damsInRajasthan.add("Jagpura");
		damsInRajasthan.add("Jai Samand");
		damsInRajasthan.add("Jaisamand");
		damsInRajasthan.add("Jakham");
		damsInRajasthan.add("Jaswant");
		damsInRajasthan.add("Jawai");
		damsInRajasthan.add("Jawahar Sagar");

		Collection<String> damsInSikkim = new ArrayList<String>();

		damsInSikkim.add("Rangit III");
		damsInSikkim.add("Rangpo");
		damsInSikkim.add("Rongli");
		damsInSikkim.add("Teesta -V");
		damsInSikkim.add("Teesta-III");
		damsInSikkim.add("Teesta-IV");

		Collection<String> damsInTamilNadu = new ArrayList<String>();

		damsInTamilNadu.add("Aanaimaduvu");
		damsInTamilNadu.add("Adavinainarkovil");
		damsInTamilNadu.add("Aliyar");
		damsInTamilNadu.add("Amaravathi");
		damsInTamilNadu.add("Anaikuttam");
		damsInTamilNadu.add("Andiappanur");
		damsInTamilNadu.add("Avalanche");
		damsInTamilNadu.add("Barur");
		damsInTamilNadu.add("Berijam");
		damsInTamilNadu.add("Bungihalla Bund");
		damsInTamilNadu.add("Chembarambakkam");
		damsInTamilNadu.add("Chinnar");
		damsInTamilNadu.add("Chittar");
		damsInTamilNadu.add("Chittar II");
		damsInTamilNadu.add("East Varahapallam");
		damsInTamilNadu.add("Emerald");
		damsInTamilNadu.add("Eravangalar");
		damsInTamilNadu.add("Gatana");
		damsInTamilNadu.add("Glenmorgan");
		damsInTamilNadu.add("Glenmorgan Forbay");
		damsInTamilNadu.add("Golwarpatti");
		damsInTamilNadu.add("Gomukhinadi");
		damsInTamilNadu.add("Gundar");
		damsInTamilNadu.add("Gunderipallam");
		damsInTamilNadu.add("Highwavys");
		damsInTamilNadu.add("Irukkangudi");
		damsInTamilNadu.add("Kadamparai");
		damsInTamilNadu.add("	Kamraju Sagar");
		damsInTamilNadu.add("Kariakoil");
		damsInTamilNadu.add("Karuppanadhi");
		damsInTamilNadu.add("Kelavarapalli");
		damsInTamilNadu.add("Kesarigulihalla");
		damsInTamilNadu.add("Kodaganar");
		damsInTamilNadu.add("Kodumudiyar");
		damsInTamilNadu.add("Krishnagiri");
		damsInTamilNadu.add("Kullursandai");
		damsInTamilNadu.add("Kundah Palam");
		damsInTamilNadu.add("Kuppanatham");
		damsInTamilNadu.add("Kuthiraiyar");
		damsInTamilNadu.add("Kuttiyadi");
		damsInTamilNadu.add("Kuttiyar");
		damsInTamilNadu.add("Lower Bhavani");
		damsInTamilNadu.add("	Lower Kodayar");
		damsInTamilNadu.add("Lower Nirar");
		damsInTamilNadu.add("Mambazhathuraiyar");
		damsInTamilNadu.add("Manalar");
		damsInTamilNadu.add("Manimukthanadhi");
		damsInTamilNadu.add("Manimuthar");
		damsInTamilNadu.add("Manjalar");
		damsInTamilNadu.add("Maravakandi Forbay");
		damsInTamilNadu.add("Marudhanadi");
		damsInTamilNadu.add("Mettur");
		damsInTamilNadu.add("Mirugandanadhi");
		damsInTamilNadu.add("Mordhana");
		damsInTamilNadu.add("Moyar Forebay");
		damsInTamilNadu.add("Mukurthy");
		damsInTamilNadu.add("Nagavathi");
		damsInTamilNadu.add("Nallathangal Odai");
		damsInTamilNadu.add("Nambiar");
		damsInTamilNadu.add("Nanganjiyar");
		damsInTamilNadu.add("Nilayur Bed");
		damsInTamilNadu.add("Noyyal Athupalayam");
		damsInTamilNadu.add("Noyyal Orathupalayam");
		damsInTamilNadu.add("Palar Porundalar");
		damsInTamilNadu.add("Pambar");
		damsInTamilNadu.add("Papanasam");
		damsInTamilNadu.add("Parappalar");
		damsInTamilNadu.add("ParsonS Valley");
		damsInTamilNadu.add("Pechiparai");
		damsInTamilNadu.add("Pegumbahallah Forebay");
		damsInTamilNadu.add("Periyar Forebay");
		damsInTamilNadu.add("Perumpallam");
		damsInTamilNadu.add("Perunchani");
		damsInTamilNadu.add("Pilavukkal Kovilar");
		damsInTamilNadu.add("Pilavukkal Periyar");
		damsInTamilNadu.add("Pillur");
		damsInTamilNadu.add("Poigaiyar");
		damsInTamilNadu.add("Ponnaniar");
		damsInTamilNadu.add("Poondi");
		damsInTamilNadu.add("Porthimund");
		damsInTamilNadu.add("Puthen");
		damsInTamilNadu.add("Pykara");
		damsInTamilNadu.add("Rajathope Kanar");
		damsInTamilNadu.add("Ramanadhi");
		damsInTamilNadu.add("Sathanur");
		damsInTamilNadu.add("Sathiyar");
		damsInTamilNadu.add("Servalar");
		damsInTamilNadu.add("Shanmuganadhi");
		damsInTamilNadu.add("Shenbagathope");
		damsInTamilNadu.add("Sholayar");
		damsInTamilNadu.add("Shoolagiri Chinnar");
		damsInTamilNadu.add("Siddhamalli");
		damsInTamilNadu.add("Sothupparai");
		damsInTamilNadu.add("Thirumurthi");
		damsInTamilNadu.add("Thoppaiyar");
		damsInTamilNadu.add("Thumblahalli");
		damsInTamilNadu.add("Uppar( Erode)");
		damsInTamilNadu.add("Upper Aliyar");
		damsInTamilNadu.add("Upper Bhavani");
		damsInTamilNadu.add("Upper Kodayar");
		damsInTamilNadu.add("Upper Kodayar Diversion");
		damsInTamilNadu.add("Vadakku Paichaiyar");
		damsInTamilNadu.add("Vaigai");
		damsInTamilNadu.add("Vaniar");
		damsInTamilNadu.add("Varadhamanadhi");
		damsInTamilNadu.add("Varattar");
		damsInTamilNadu.add("Varattupallam");
		damsInTamilNadu.add("Vattamalaikarai Odai");
		damsInTamilNadu.add("Vembakottai");
		damsInTamilNadu.add("Vennir-Ar");
		damsInTamilNadu.add("Vidur");
		damsInTamilNadu.add("West Varahapallam Weir");
		damsInTamilNadu.add("Western Catchment No. I");
		damsInTamilNadu.add("Western Catchment No. II");
		damsInTamilNadu.add("Western Catchment No. III");
		damsInTamilNadu.add("Willington");
		damsInTamilNadu.add("gadag");

		Collection<String> damsInTelangana = new ArrayList<String>();

		damsInTelangana.add("Ada Village - Peddavagu");
		damsInTelangana.add("Akkampalli");
		damsInTelangana.add("Bandlavagu");
		damsInTelangana.add("Bazarthathnur");
		damsInTelangana.add("Bethampudi");
		damsInTelangana.add("Bheemanpally");
		damsInTelangana.add("Boath");
		damsInTelangana.add("Boggulavagu");
		damsInTelangana.add("Budhpur");
		damsInTelangana.add("Chelamelavagu");
		damsInTelangana.add("Choutaplly Hanuman Reddy Lift");
		damsInTelangana.add("Dantakani Cheruvu");
		damsInTelangana.add("Devathlacheru");
		damsInTelangana.add("Dharamsagar");
		damsInTelangana.add("Dindi");
		damsInTelangana.add("Fox Sagar");
		damsInTelangana.add("Gandipally");
		damsInTelangana.add("Ghanpur Lake");
		damsInTelangana.add("Gidda Cheru, Yellareddypet");
		damsInTelangana.add("Gopaldinne");
		damsInTelangana.add("Gudipalligattu");
		damsInTelangana.add("Gujjulavagu , Gandhari");
		damsInTelangana.add("	Gundetivagu Cheroo, Reddygudem");
		damsInTelangana.add("Gundlavagu");
		damsInTelangana.add("Himayat Sagar");
		damsInTelangana.add("Indirammasagar, Anajpur");
		damsInTelangana.add("Jutpally Weir/Jutepally");
		damsInTelangana.add("Kaddam");
		damsInTelangana.add("Kajjerla Anicut");
		damsInTelangana.add("Kakarvani");
		damsInTelangana.add("Kandlapalle Cheruvu");
		damsInTelangana.add("Kesavari Samudram");
		damsInTelangana.add("Kinnerasani");
		damsInTelangana.add("Koil Sagar");
		damsInTelangana.add("Komaram Bheem");
		damsInTelangana.add("Komsettipally");
		damsInTelangana.add("Kothacheru, Mamdabad");
		damsInTelangana.add("Kotipally Vagu");
		damsInTelangana.add("Koulasanala");
		damsInTelangana.add("Krishnasamudram");
		damsInTelangana.add("Kuppakanti");
		damsInTelangana.add("Lakhnapur");
		damsInTelangana.add("Lakhnavaram");
		damsInTelangana.add("Lankasagar");
		damsInTelangana.add("Adloor Yellareddy");
		damsInTelangana.add("Bibipet");
		damsInTelangana.add("Brahmanpally");
		damsInTelangana.add("Large , Dharmaraopet");
		damsInTelangana.add("Large , Garepally");
		damsInTelangana.add("Garla");
		damsInTelangana.add("Husnabad");
		damsInTelangana.add("Ibrahimpatnam");
		damsInTelangana.add("Indalwai");
		damsInTelangana.add("Jangampally");
		damsInTelangana.add("Kachapur");
		damsInTelangana.add("Kamareddy");
		damsInTelangana.add("Kapuram");
		damsInTelangana.add("Khajar");
		damsInTelangana.add("Manchippa");
		damsInTelangana.add("Mustabad");
		damsInTelangana.add("Ped allareddy");
		damsInTelangana.add("Pulkal");
		damsInTelangana.add("Raviryal");
		damsInTelangana.add("Shameerpet");
		damsInTelangana.add("Sultanabad");
		damsInTelangana.add("Uppalwai");
		damsInTelangana.add("Vilasagar");
		damsInTelangana.add("Lower Manair");
		damsInTelangana.add("Malikacheru");
		damsInTelangana.add("Mallammacheruvu Saralnagar");
		damsInTelangana.add("Malluruvagu");
		damsInTelangana.add("Mathadivagu");
		damsInTelangana.add("Hajipur");
		damsInTelangana.add("Medi Cheru");
		damsInTelangana.add("Melammacheru");
		damsInTelangana.add("Mid Manair");
		damsInTelangana.add("Modikuntavagu");
		damsInTelangana.add("Mothe Cheruvu");
		damsInTelangana.add("Mukkamamidi");
		damsInTelangana.add("Mulavagu");
		damsInTelangana.add("Munneru");
		damsInTelangana.add("Musi");
		damsInTelangana.add("Nagarjuna Sagar");
		damsInTelangana.add("Nagarjunasagar Tail Pond");
		damsInTelangana.add("Nallacheru");
		damsInTelangana.add("Nallavagu");
		damsInTelangana.add("Namaz Cheru");
		damsInTelangana.add("Kasula");
		damsInTelangana.add("Neelwai");
		damsInTelangana.add("Bellempally");
		damsInTelangana.add("Kothur");
		damsInTelangana.add("Nizam Sagar");
		damsInTelangana.add("Ookachettivagu");
		damsInTelangana.add("Oora Cheru");
		damsInTelangana.add("Osman Sagar");
		damsInTelangana.add("Pakhal Lake");
		damsInTelangana.add("Palair");
		damsInTelangana.add("Palemvagu");
		damsInTelangana.add("Pedda Cheru");
		damsInTelangana.add("Challasamudram");
		damsInTelangana.add("Chintapalli");
		damsInTelangana.add("Inapur");
		damsInTelangana.add("Indurthy");
		damsInTelangana.add("Kodad");
		damsInTelangana.add("Lingapur");
		damsInTelangana.add("Potharam");
		damsInTelangana.add("Shivanagudem");
		damsInTelangana.add("Soan");
		damsInTelangana.add("Stambampally");
		damsInTelangana.add("Swamulavari Lingotam");
		damsInTelangana.add("Thangadpally");
		damsInTelangana.add("Vellutla");
		damsInTelangana.add("Yellareddy");
		damsInTelangana.add("Yelupugonda");
		damsInTelangana.add("Lokaram");
		damsInTelangana.add("Lokurthy");
		damsInTelangana.add("Ragaboinagudem");
		damsInTelangana.add("Lingal");
		damsInTelangana.add("Peddavagu");
		damsInTelangana.add("Peddavagu-Jagannathpur");
		damsInTelangana.add("Perval");
		damsInTelangana.add("Pocharam");
		damsInTelangana.add("Polkicheru");
		damsInTelangana.add("Posanipeta Cheruvu");
		damsInTelangana.add("Jurala");
		damsInTelangana.add("Narsapur");
		damsInTelangana.add("Ramadugu");
		damsInTelangana.add("Ramappa");
		damsInTelangana.add("Rangasamudram");
		damsInTelangana.add("Rasulacheru");
		damsInTelangana.add("Salivagu");
		damsInTelangana.add("Sangambanda");
		damsInTelangana.add("Sankarasamudram");
		damsInTelangana.add("Sarala Sagar");
		damsInTelangana.add("Sarpanapally");
		damsInTelangana.add("Sat Dodarna");
		damsInTelangana.add("Sathanala");
		damsInTelangana.add("Shanigram");
		damsInTelangana.add("Singaraya");
		damsInTelangana.add("Singasamudram");
		damsInTelangana.add("Singhabhoopalem");
		damsInTelangana.add("Singur");
		damsInTelangana.add("Sirala");
		damsInTelangana.add("Sriram Sagar");
		damsInTelangana.add("Srisailam");
		damsInTelangana.add("Srivari Samudram");
		damsInTelangana.add("Stambala Cheru");
		damsInTelangana.add("Suddavagu");
		damsInTelangana.add("Suryanarayanacheru");
		damsInTelangana.add("Swarna");
		damsInTelangana.add("Taliperu");
		damsInTelangana.add("Tatikunta");
		damsInTelangana.add("Thalla Cheru");
		damsInTelangana.add("Thotapally");
		damsInTelangana.add("Upper Manair");
		damsInTelangana.add("Utkoor Marepall");
		damsInTelangana.add("Vattivagu");
		damsInTelangana.add("Veerladevi Cheru");
		damsInTelangana.add("Vemular");
		damsInTelangana.add("Wyra");
		damsInTelangana.add("Yellur");
		damsInTelangana.add("Yenukunta");
		damsInTelangana.add("Yerravagu");
		damsInTelangana.add("Zildartippa");

		Collection<String> damsInUttarpradesh = new ArrayList<String>();

		damsInUttarpradesh.add("Adwa");
		damsInUttarpradesh.add("Afzalgarh");
		damsInUttarpradesh.add("Ahraura");
		damsInUttarpradesh.add("Aunjhar");
		damsInUttarpradesh.add("Bachara");
		damsInUttarpradesh.add("Baghel Khand");
		damsInUttarpradesh.add("Baghla");
		damsInUttarpradesh.add("Balui Bandh");
		damsInUttarpradesh.add("Balui");
		damsInUttarpradesh.add("Banjari Kalan");
		damsInUttarpradesh.add("Barwa");
		damsInUttarpradesh.add("Barwa Sagar");
		damsInUttarpradesh.add("Barwar");
		damsInUttarpradesh.add("Barwatola");
		damsInUttarpradesh.add("Bhagwan Pur");
		damsInUttarpradesh.add("Bhainsora");
		damsInUttarpradesh.add("Bhonka");
		damsInUttarpradesh.add("Chandra Prabha");
		damsInUttarpradesh.add("Chandrawal");
		damsInUttarpradesh.add("Chittaurgarh");
		damsInUttarpradesh.add("Deori");
		damsInUttarpradesh.add("Dhandhraul");
		damsInUttarpradesh.add("Dhenkwan");
		damsInUttarpradesh.add("Dongia");
		damsInUttarpradesh.add("Dongri");
		damsInUttarpradesh.add("Ganeshpur");
		damsInUttarpradesh.add("Garhwa");
		damsInUttarpradesh.add("Ghooga");
		damsInUttarpradesh.add("Ghori");
		damsInUttarpradesh.add("Girgity");
		damsInUttarpradesh.add("Gointha");
		damsInUttarpradesh.add("Govind Sagar");
		damsInUttarpradesh.add("Gularia");
		damsInUttarpradesh.add("Gunta");
		damsInUttarpradesh.add("Hinauti");
		damsInUttarpradesh.add("Jaiwanti");
		damsInUttarpradesh.add("Jamini");
		damsInUttarpradesh.add("Jirgo");
		damsInUttarpradesh.add("Jogendra");
		damsInUttarpradesh.add("Kabrai");
		damsInUttarpradesh.add("Kachnoda");
		damsInUttarpradesh.add("Kargara");
		damsInUttarpradesh.add("Keolari");
		damsInUttarpradesh.add("Khairman");
		damsInUttarpradesh.add("Khandeha");
		damsInUttarpradesh.add("Khapatia");
		damsInUttarpradesh.add("Khirihata");
		damsInUttarpradesh.add("Kohar Gaddi");
		damsInUttarpradesh.add("Kota");
		damsInUttarpradesh.add("Kotra Khambha");
		damsInUttarpradesh.add("Kuba Khurd");
		damsInUttarpradesh.add("Lachura");
		damsInUttarpradesh.add("Lower Khajuri");
		damsInUttarpradesh.add("Majhgawan");
		damsInUttarpradesh.add("Matatila");
		damsInUttarpradesh.add("Maudaha");
		damsInUttarpradesh.add("Meja");
		damsInUttarpradesh.add("Moosakhand");
		damsInUttarpradesh.add("Muirpur");
		damsInUttarpradesh.add("Murtia");
		damsInUttarpradesh.add("Nagwa");
		damsInUttarpradesh.add("Nanauti");
		damsInUttarpradesh.add("Narson");
		damsInUttarpradesh.add("Naugarh");
		damsInUttarpradesh.add("Newari");
		damsInUttarpradesh.add("Obra");
		damsInUttarpradesh.add("Ohen");
		damsInUttarpradesh.add("Pachwara Lake");
		damsInUttarpradesh.add("Pahari");
		damsInUttarpradesh.add("Pahuj");
		damsInUttarpradesh.add("Patharai");
		damsInUttarpradesh.add("Pili");
		damsInUttarpradesh.add("Ragura");
		damsInUttarpradesh.add("Raipura");
		damsInUttarpradesh.add("Rajghat");
		damsInUttarpradesh.add("Rajkhar");
		damsInUttarpradesh.add("Rampur");
		damsInUttarpradesh.add("Rampur Kalyangarh");
		damsInUttarpradesh.add("Rampur Pindaria");
		damsInUttarpradesh.add("Rihand");
		damsInUttarpradesh.add("Rohini");
		damsInUttarpradesh.add("Sajnam");
		damsInUttarpradesh.add("Saktesh Garh");
		damsInUttarpradesh.add("Salarpur");
		damsInUttarpradesh.add("Saprar");
		damsInUttarpradesh.add("Sarai Garh");
		damsInUttarpradesh.add("Sarda Sagar");
		damsInUttarpradesh.add("Semri");
		damsInUttarpradesh.add("Shahjad");
		damsInUttarpradesh.add("Siori Lake");
		damsInUttarpradesh.add("Sirsi");
		damsInUttarpradesh.add("Sukhra");
		damsInUttarpradesh.add("Suswar");
		damsInUttarpradesh.add("Upper Khajuri");
		damsInUttarpradesh.add("Urmil");
		damsInUttarpradesh.add("Vijaipur");

		Collection<String> damsInTripura = new ArrayList<String>();

		damsInTripura.add("Gumti Hydro");

		Collection<String> damsInUttarakhand = new ArrayList<String>();

		damsInUttarakhand.add("Baigul");
		damsInUttarakhand.add("Baur");
		damsInUttarakhand.add("Bhimtal");
		damsInUttarakhand.add("Dhauliganga");
		damsInUttarakhand.add("Dhora");
		damsInUttarakhand.add("Haripura");
		damsInUttarakhand.add("Ichari");
		damsInUttarakhand.add("Jamrani");
		damsInUttarakhand.add("Koteshwar");
		damsInUttarakhand.add("Lakhwar");
		damsInUttarakhand.add("Maneri");
		damsInUttarakhand.add("Nanak Sagar");
		damsInUttarakhand.add("Ramganga");
		damsInUttarakhand.add("Tehri");
		damsInUttarakhand.add("Tumaria");

		Collection<String> damsInWestBengal = new ArrayList<String>();

		damsInWestBengal.add("Bakreshwar");
		damsInWestBengal.add("Bandhu");
		damsInWestBengal.add("Bara Mandira");
		damsInWestBengal.add("Barabhum");
		damsInWestBengal.add("Beko");
		damsInWestBengal.add("Dangrajhore");
		damsInWestBengal.add("Dimu");
		damsInWestBengal.add("Futiary");
		damsInWestBengal.add("Golamarajore");
		damsInWestBengal.add("Hanumata");
		damsInWestBengal.add("Hinglow Irrigation Scheme");
		damsInWestBengal.add("Kangsabati Kumari");
		damsInWestBengal.add("Kanjan");
		damsInWestBengal.add("Karrior");
		damsInWestBengal.add("Khairabera");
		damsInWestBengal.add("Kumari");
		damsInWestBengal.add("Lipania");
		damsInWestBengal.add("Lower : PPSP");
		damsInWestBengal.add("Moutorejore");
		damsInWestBengal.add("Muruguma");
		damsInWestBengal.add("Nachan Irri. Scheme");
		damsInWestBengal.add("Paraga Irri. Scheme");
		damsInWestBengal.add("Patloi");
		damsInWestBengal.add("Ramchandrapur");
		damsInWestBengal.add("Rupai");
		damsInWestBengal.add("Saharajore Irri. Scheme");
		damsInWestBengal.add("Sali");
		damsInWestBengal.add("Taragonia Irri. Scheme");
		damsInWestBengal.add("Tatko");
		damsInWestBengal.add("Teesta-III Lower");
		damsInWestBengal.add("Teesta-IV Lower");
		damsInWestBengal.add("Turga Irri. Scheme");
		damsInWestBengal.add("Upper Dam: PPSP");
		damsInWestBengal.add("malayalam");

		Collection<String> damsInIndia = new ArrayList<String>();
		
		damsInIndia.addAll(damsInKarnataka);
		damsInIndia.addAll(damsInAndhraPradesh);
		damsInIndia.addAll(damsInArunachal);
		damsInIndia.addAll(damsInAssam);
		damsInIndia.addAll(damsInBihar);
		damsInIndia.addAll(damsInChattisgarh);
		damsInIndia.addAll(damsInGoa);
		damsInIndia.addAll(damsInGujarat);
		damsInIndia.addAll(damsInHaryana);
		damsInIndia.addAll(damsInHimachalPradesh);
		damsInIndia.addAll(damsInJharkand);
		damsInIndia.addAll(damsInKerala);
		damsInIndia.addAll(damsInMadhyaPradesh);
		damsInIndia.addAll(damsInMaharashtra);
		damsInIndia.addAll(damsInManipur);
		damsInIndia.addAll(damsInMeghalaya);
		damsInIndia.addAll(damsInMizoram);
		damsInIndia.addAll(damsInNagaland);
		damsInIndia.addAll(damsInOdisha);
		damsInIndia.addAll(damsInPunjab);
		damsInIndia.addAll(damsInRajasthan);
		damsInIndia.addAll(damsInSikkim);
		damsInIndia.addAll(damsInTamilNadu);
		damsInIndia.addAll(damsInTripura);
		damsInIndia.addAll(damsInUttarakhand);
		damsInIndia.addAll(damsInTelangana);
		damsInIndia.addAll(damsInUttarpradesh);

		System.out.println("====================Dam names starting with T======================");
		Iterator<String> iterator = damsInIndia.iterator();

		while (iterator.hasNext()) {
			String dam = (String) iterator.next();

			if (dam.startsWith("T")) {
				System.out.println("The dam name starting with T : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names ending with ra======================");
		Iterator<String> iterator1 = damsInIndia.iterator();
		while (iterator1.hasNext()) {
			String dam = (String) iterator1.next();

			if (dam.endsWith("ra")) {
				System.out.println("The dam name ending with ra : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dams name length more than 15======================");
		Iterator<String> iterator2 = damsInIndia.iterator();
		while (iterator2.hasNext()) {
			String dam = (String) iterator2.next();

			if (dam.length() >= 15) {
				System.out.println("dam name length more than 15 : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names in upperCase======================");
		Iterator<String> iterator6 = damsInIndia.iterator();
		while (iterator6.hasNext()) {
			String dam = (String) iterator6.next();
			String upperDam = dam.toUpperCase();

			if (upperDam.equals(dam)) {
				System.out.println("dam name in upperCase : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names in lowerCase======================");
		Iterator<String> iterator7 = damsInIndia.iterator();
		while (iterator7.hasNext()) {
			String dam = (String) iterator7.next();

			String lowerDam = dam.toLowerCase();

			if (lowerDam.equals(dam)) {

				System.out.println("dam name in lowerCase : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================checking for palindrome======================");
		Iterator<String> iterator3 = damsInIndia.iterator();
		while (iterator3.hasNext()) {

			String dam = (String) iterator3.next();
			int len = dam.length() - 1;
			int i, j, ch = 0;
			for (i = 0, j = len; i <= len; i++, j--) {
				if (dam.charAt(i) != dam.charAt(j)) {
					ch = 1;
					break;
				}
			}
			if (ch == 1) {

			} else {
				System.out.println("the dame name is planidrome : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names having letter p======================");
		System.out.println("size of collection before removing : " + damsInIndia.size());

		Iterator<String> iterator5 = damsInIndia.iterator();
		while (iterator5.hasNext()) {
			String dam = (String) iterator5.next();

			if (dam.contains("P") || dam.contains("p")) {
				System.out.println("removed dam name which contains p : " + dam);
				iterator5.remove();

			}

		}
		System.out.println("size of collection after removing : " + damsInIndia.size());

	}

}
